### Load tensorflow

In [186]:
import tensorflow as tf

In [187]:
#Reset Default graph - Needed only for Jupyter notebook
tf.reset_default_graph()

### Collect Data

In [188]:
import pandas as pd

In [189]:
data = pd.read_csv('prices.csv')

### Check all columns in the dataset

In [190]:
data.shape

(851264, 7)

In [191]:
data.columns

Index(['date', 'symbol', 'open', 'close', 'low', 'high', 'volume'], dtype='object')

### Drop columns `date` and  `symbol`

In [192]:
data.drop(['date','symbol'],axis=1,inplace=True)

In [193]:
data.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

### Consider only first 1000 rows in the dataset for building feature set and target set

In [194]:
X=data.loc[:999,['open','low','high','volume']]
Y=data.loc[:999,['close']]

In [195]:
X.shape

(1000, 4)

In [196]:
Y.shape

(1000, 1)

### Divide the data into train and test sets

In [197]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

## Building the graph in tensorflow

1.Define input data placeholders

In [198]:
#Input features
x = tf.placeholder(shape=[None,4],dtype=tf.float32, name='x-input')

#Normalize the data
x_n = tf.nn.l2_normalize(x,1)

#Actual Prices
y_ = tf.placeholder(shape=[None,1],dtype=tf.float32, name='y-input')

2.Define Weights and Bias

In [199]:
W = tf.Variable(tf.zeros(shape=[4,1]), name="Weights")
b = tf.Variable(tf.zeros(shape=[1]),name="Bias")

3.Prediction

In [200]:
y_pred = tf.add(tf.matmul(x_n,W),b,name='output')

4.Loss (Cost) Function [Mean square error]

In [201]:
loss = tf.reduce_mean(tf.square(y_pred-y_),name='Loss')

5.GradientDescent Optimizer to minimize Loss [GradientDescentOptimizer]

In [202]:
train_op = tf.train.GradientDescentOptimizer(0.03).minimize(loss)

## Execute the Graph for 100 epochs and observe the loss

In [203]:
#start graph Execution
sess = tf.Session()

# variables need to be initialized before we can use them
sess.run(tf.global_variables_initializer())

#how many times data need to be shown to model
training_epochs = 100

In [204]:
for epoch in range(training_epochs):
            
    #Calculate train_op and loss
    _, train_loss = sess.run([train_op,loss],feed_dict={x:X_train, y_:Y_train})
    
    if epoch % 10 == 0:
        print ('Training loss at step: ', epoch, ' is ', train_loss)

Training loss at step:  0  is  7817.284
Training loss at step:  10  is  3684.1895
Training loss at step:  20  is  3363.6152
Training loss at step:  30  is  3338.7507
Training loss at step:  40  is  3336.8218
Training loss at step:  50  is  3336.6726
Training loss at step:  60  is  3336.6606
Training loss at step:  70  is  3336.6597
Training loss at step:  80  is  3336.6594
Training loss at step:  90  is  3336.66


### Get the shapes and values of W and b

Hint: Use sess.run(W) to get W.

In [205]:
print(W.shape)
sess.run(W)

(4, 1)


array([[2.3045467e-02],
       [2.2827424e-02],
       [2.3217712e-02],
       [3.3468628e+01]], dtype=float32)

In [206]:
print(b.shape)
sess.run(b)

(1,)


array([33.46864], dtype=float32)

### Find the Absolute mean square loss difference between training and testing loss.

In [207]:
test_loss = sess.run(tf.reduce_sum(loss),feed_dict={x:X_test, y_:Y_test})

In [208]:
abs_mse_loss=abs(train_loss-test_loss)
abs_mse_loss

329.46802

In [209]:
sess.close()

### Linear Classification using Keras

### Building the simple Neural Network in Keras with one neuron in the dense hidden layer.
#### Use Mean square error as loss function and sgd as optimizer

In [77]:
#Initialize Sequential Graph (model)
model = tf.keras.models.Sequential()

#Normalize input data
model.add(tf.keras.layers.Dense(1,input_shape=(4,)))

#Add Dense layer for prediction 
model.add(tf.keras.layers.Dense(1,activation='softmax'))

#Compile the model - add Loss and Gradient Descent optimizer
model.compile(optimizer='sgd', loss='mse')

### Execute the model

In [107]:
model.fit(X_train, Y_train, epochs=100)

Epoch 1/100
800/800 [==============================] - 0s 474us/sample - loss: 8246.4213
Epoch 2/100
800/800 [==============================] - 0s 63us/sample - loss: 8246.4211
Epoch 3/100
800/800 [==============================] - 0s 51us/sample - loss: 8246.4211
Epoch 4/100
800/800 [==============================] - 0s 58us/sample - loss: 8246.4211
Epoch 5/100
800/800 [==============================] - 0s 66us/sample - loss: 8246.4213
Epoch 6/100
800/800 [==============================] - 0s 60us/sample - loss: 8246.4211
Epoch 7/100
800/800 [==============================] - 0s 60us/sample - loss: 8246.4210
Epoch 8/100
800/800 [==============================] - 0s 58us/sample - loss: 8246.4212
Epoch 9/100
800/800 [==============================] - 0s 61us/sample - loss: 8246.4212
Epoch 10/100
800/800 [==============================] - 0s 65us/sample - loss: 8246.4213
Epoch 11/100
800/800 [==============================] - 0s 65us/sample - loss: 8246.4212
Epoch 12/100
800/800 [=======

800/800 [==============================] - 0s 59us/sample - loss: 8246.4213
Epoch 94/100
800/800 [==============================] - 0s 58us/sample - loss: 8246.4211
Epoch 95/100
800/800 [==============================] - 0s 61us/sample - loss: 8246.4211
Epoch 96/100
800/800 [==============================] - 0s 54us/sample - loss: 8246.4212
Epoch 97/100
800/800 [==============================] - 0s 55us/sample - loss: 8246.4211
Epoch 98/100
800/800 [==============================] - 0s 50us/sample - loss: 8246.4211
Epoch 99/100
800/800 [==============================] - 0s 50us/sample - loss: 8246.4211
Epoch 100/100
800/800 [==============================] - 0s 53us/sample - loss: 8246.4212


### Classification using Keras 

### Load the given Iris data using pandas (Iris.csv)

In [79]:
iris_data=pd.read_csv('iris.csv')
iris_data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

### Splitting the data into feature set and target set

In [83]:
features=iris_data.loc[:,['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
target=iris_data.loc[:,['Species']]

### Target set has different categories. So, Label encode them. And convert into one-hot vectors using get_dummies in pandas.

In [91]:
from sklearn.preprocessing import LabelEncoder

In [97]:
Le=LabelEncoder()
label=Le.fit_transform(target)

C:\Users\Shreyaspatil\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [98]:
import pandas as pd

In [101]:
target=pd.DataFrame(pd.get_dummies(label))
target.head()

0  1  2
0  1  0  0
1  1  0  0
2  1  0  0
3  1  0  0
4  1  0  0

### Divide the dataset into Training and test (70:30)

In [102]:
X1_train,X1_test,Y1_train,Y1_test=train_test_split(features,target,test_size=0.3)

### Model
Build the model with following layers: <br>
1. First dense layer with 10 neurons with input shape 4 (according to the feature set) <br>
2. Second Dense layer with 8 neurons <br>
3. Output layer with 3 neurons with softmax activation (output layer, 3 neurons as we have 3 classes) <br>
4. Use SGD and categorical_crossentropy loss 

In [121]:
#Initialize Sequential Graph (model)
model1 = tf.keras.models.Sequential()

#Normalize input data
model1.add(tf.keras.layers.Dense(10,input_shape=(4,)))

model1.add(tf.keras.layers.Dense(8,activation='relu'))
#Add Dense layer for prediction 
model1.add(tf.keras.layers.Dense(3,activation='softmax'))

model1.compile(optimizer='sgd', loss='categorical_crossentropy',metrics=['accuracy'])

### Fitting the model and predicting 

In [146]:
model1.fit(X1_train, Y1_train, epochs=50)

Epoch 1/50
105/105 [==============================] - 0s 124us/sample - loss: 0.1700 - acc: 0.9714
Epoch 2/50
105/105 [==============================] - 0s 124us/sample - loss: 0.1706 - acc: 0.9714
Epoch 3/50
105/105 [==============================] - 0s 114us/sample - loss: 0.1671 - acc: 0.9714
Epoch 4/50
105/105 [==============================] - 0s 114us/sample - loss: 0.1714 - acc: 0.9810
Epoch 5/50
105/105 [==============================] - 0s 143us/sample - loss: 0.1676 - acc: 0.9810
Epoch 6/50
105/105 [==============================] - 0s 105us/sample - loss: 0.2089 - acc: 0.9429
Epoch 7/50
105/105 [==============================] - 0s 133us/sample - loss: 0.1636 - acc: 0.9714
Epoch 8/50
105/105 [==============================] - 0s 133us/sample - loss: 0.1635 - acc: 0.9619
Epoch 9/50
105/105 [==============================] - 0s 124us/sample - loss: 0.1572 - acc: 0.9810
Epoch 10/50
105/105 [==============================] - 0s 114us/sample - loss: 0.1682 - acc: 0.9714
Epoch 11/

In [147]:
score=model1.evaluate(X1_test,Y1_test)

45/45 [==============================] - 0s 133us/sample - loss: 0.1333 - acc: 0.9778


### Report Accuracy of the predicted values

In [148]:
print("Accuracy =",score[1]*100)

Accuracy = 97.77777791023254


In [149]:
predicted=model1.predict(X1_test)

In [150]:
predicted

array([[5.97418875e-05, 1.72722742e-01, 8.27217519e-01],
       [7.67400162e-03, 8.77839863e-01, 1.14486188e-01],
       [3.35538480e-03, 7.69436479e-01, 2.27208197e-01],
       [1.03762476e-02, 8.99338424e-01, 9.02852714e-02],
       [9.79797304e-01, 2.02026647e-02, 5.13293728e-08],
       [3.58077581e-03, 8.48313987e-01, 1.48105249e-01],
       [5.17400913e-05, 1.57287538e-01, 8.42660666e-01],
       [5.71487035e-05, 1.47726059e-01, 8.52216840e-01],
       [9.92430389e-01, 7.56964693e-03, 2.17108331e-09],
       [1.72814354e-02, 9.29514825e-01, 5.32038100e-02],
       [1.26487180e-03, 5.29916584e-01, 4.68818575e-01],
       [1.48223713e-04, 2.13072225e-01, 7.86779523e-01],
       [9.86561477e-01, 1.34384921e-02, 2.89239530e-08],
       [4.35698126e-03, 9.21793044e-01, 7.38500059e-02],
       [9.80371296e-01, 1.96286123e-02, 5.87637281e-08],
       [9.95741487e-01, 4.25854651e-03, 1.03339204e-09],
       [6.98447329e-05, 2.75252402e-01, 7.24677742e-01],
       [5.50697405e-06, 4.55795

In [151]:
import numpy as np

In [152]:
result_test=np.argmax(predicted,axis=1)

In [153]:
result_test

array([2, 1, 1, 1, 0, 1, 2, 2, 0, 1, 1, 2, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0,
       2, 0, 1, 1, 0, 1, 2, 2, 2, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0, 0, 2, 0,
       2], dtype=int64)

In [154]:
Y1_test=np.array(Y1_test)

In [155]:
r_test=np.argmax(Y1_test,axis=1)

In [156]:
r_test

array([2, 1, 1, 1, 0, 1, 2, 2, 0, 1, 1, 1, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0,
       2, 0, 1, 1, 0, 1, 2, 2, 2, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0, 0, 2, 0,
       2], dtype=int64)

In [157]:
from sklearn.metrics import accuracy_score

In [158]:
accuracy=accuracy_score(r_test,result_test)

In [159]:
accuracy

0.9777777777777777